//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimsmart.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backupdelete {
            get {
                object obj = ResourceManager.GetObject("backupdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backupmakenew {
            get {
                object obj = ResourceManager.GetObject("backupmakenew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backuprestore {
            get {
                object obj = ResourceManager.GetObject("backuprestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup copy of database.
        /// </summary>
        public static string bckDataH {
            get {
                return ResourceManager.GetString("bckDataH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a backup copy of database failed..
        /// </summary>
        public static string bckDataKO {
            get {
                return ResourceManager.GetString("bckDataKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup copy of database was created at {0}..
        /// </summary>
        public static string bckDataOK {
            get {
                return ResourceManager.GetString("bckDataOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string cbPauseResumeText {
            get {
                return ResourceManager.GetString("cbPauseResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string cbPauseText {
            get {
                return ResourceManager.GetString("cbPauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect the electrodes.
        /// </summary>
        public static string chActive {
            get {
                return ResourceManager.GetString("chActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel disconnected.
        /// </summary>
        public static string chDisconected {
            get {
                return ResourceManager.GetString("chDisconected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string chError {
            get {
                return ResourceManager.GetString("chError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resistance is too high.
        /// </summary>
        public static string chHighResistance {
            get {
                return ResourceManager.GetString("chHighResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel inaccessible.
        /// </summary>
        public static string chInaccessible {
            get {
                return ResourceManager.GetString("chInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel inactive.
        /// </summary>
        public static string chInactive {
            get {
                return ResourceManager.GetString("chInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure is performed....
        /// </summary>
        public static string chInProgress {
            get {
                return ResourceManager.GetString("chInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure is suspended.
        /// </summary>
        public static string chPaused {
            get {
                return ResourceManager.GetString("chPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ready.
        /// </summary>
        public static string chReady {
            get {
                return ResourceManager.GetString("chReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure is restored....
        /// </summary>
        public static string chRestored {
            get {
                return ResourceManager.GetString("chRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the current....
        /// </summary>
        public static string chSetCurrent {
            get {
                return ResourceManager.GetString("chSetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close16 {
            get {
                object obj = ResourceManager.GetObject("close16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cs {
            get {
                object obj = ResourceManager.GetObject("cs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language: {0}.
        /// </summary>
        public static string curLang {
            get {
                return ResourceManager.GetString("curLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string curLang1 {
            get {
                return ResourceManager.GetString("curLang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbbackup {
            get {
                object obj = ResourceManager.GetObject("dbbackup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbcompact {
            get {
                object obj = ResourceManager.GetObject("dbcompact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is closed..
        /// </summary>
        public static string dbIsClosed {
            get {
                return ResourceManager.GetString("dbIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is open..
        /// </summary>
        public static string dbIsOpen {
            get {
                return ResourceManager.GetString("dbIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbnew {
            get {
                object obj = ResourceManager.GetObject("dbnew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbrestore {
            get {
                object obj = ResourceManager.GetObject("dbrestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &quot;{0}&quot; was truncated..
        /// </summary>
        public static string delAllMsg {
            get {
                return ResourceManager.GetString("delAllMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the entire content of table &quot;{0}&quot; to all data will be lost from the table. Do you really want to do?.
        /// </summary>
        public static string delAllQ {
            get {
                return ResourceManager.GetString("delAllQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating the table.
        /// </summary>
        public static string delAllQH {
            get {
                return ResourceManager.GetString("delAllQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows was deleted from table {1}..
        /// </summary>
        public static string delNRows {
            get {
                return ResourceManager.GetString("delNRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap deluser {
            get {
                object obj = ResourceManager.GetObject("deluser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic lesions.
        /// </summary>
        public static string dgCLesions {
            get {
                return ResourceManager.GetString("dgCLesions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic pain (non-oncogenic).
        /// </summary>
        public static string dgCPain {
            get {
                return ResourceManager.GetString("dgCPain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetic polyneuropathy.
        /// </summary>
        public static string dgDPNP {
            get {
                return ResourceManager.GetString("dgDPNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erectile disorders.
        /// </summary>
        public static string dgEDis {
            get {
                return ResourceManager.GetString("dgEDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endocrinology.
        /// </summary>
        public static string dgEndocrinology {
            get {
                return ResourceManager.GetString("dgEndocrinology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microcirculation.
        /// </summary>
        public static string dgMicrocirculation {
            get {
                return ResourceManager.GetString("dgMicrocirculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnosis has not been selected.
        /// </summary>
        public static string dgNotSelected {
            get {
                return ResourceManager.GetString("dgNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap erase {
            get {
                object obj = ResourceManager.GetObject("erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} while executing {1}.
        /// </summary>
        public static string errExecCmd {
            get {
                return ResourceManager.GetString("errExecCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application exits..
        /// </summary>
        public static string exitMsg {
            get {
                return ResourceManager.GetString("exitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this point, you can not quit..
        /// </summary>
        public static string exitNo {
            get {
                return ResourceManager.GetString("exitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit the application?.
        /// </summary>
        public static string exitQ {
            get {
                return ResourceManager.GetString("exitQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application exit.
        /// </summary>
        public static string exitQH {
            get {
                return ResourceManager.GetString("exitQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of initialization..
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hic {
            get {
                object obj = ResourceManager.GetObject("hic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Health Insurance Company.
        /// </summary>
        public static string HICEditHdr {
            get {
                return ResourceManager.GetString("HICEditHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIC &quot;{0}&quot; was updated..
        /// </summary>
        public static string HICEditMsg {
            get {
                return ResourceManager.GetString("HICEditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of HIC.
        /// </summary>
        public static string HICHdrCode {
            get {
                return ResourceManager.GetString("HICHdrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the health insurance company.
        /// </summary>
        public static string HICHdrName {
            get {
                return ResourceManager.GetString("HICHdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Health Insurance Company.
        /// </summary>
        public static string HICNewHdr {
            get {
                return ResourceManager.GetString("HICNewHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New HIC &quot;{0}&quot; was created..
        /// </summary>
        public static string HICNewMsg {
            get {
                return ResourceManager.GetString("HICNewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language has been changed to {0}.
        /// </summary>
        public static string langChanged {
            get {
                return ResourceManager.GetString("langChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string LogHdrDate {
            get {
                return ResourceManager.GetString("LogHdrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string LogHdrRecord {
            get {
                return ResourceManager.GetString("LogHdrRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string LogHdrSender {
            get {
                return ResourceManager.GetString("LogHdrSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LogHdrType {
            get {
                return ResourceManager.GetString("LogHdrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LogInfo {
            get {
                return ResourceManager.GetString("LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_ZAT {
            get {
                object obj = ResourceManager.GetObject("Logo_ZAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LogWarn {
            get {
                return ResourceManager.GetString("LogWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new database failed.
        /// </summary>
        public static string newDataKO {
            get {
                return ResourceManager.GetString("newDataKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database was created..
        /// </summary>
        public static string newDataOK {
            get {
                return ResourceManager.GetString("newDataOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to create a new database, the old one will be removed. Do you really want to do this?.
        /// </summary>
        public static string newDataQ {
            get {
                return ResourceManager.GetString("newDataQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database.
        /// </summary>
        public static string newDataQH {
            get {
                return ResourceManager.GetString("newDataQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup available..
        /// </summary>
        public static string noBacksAvail {
            get {
                return ResourceManager.GetString("noBacksAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of channels: {0}.
        /// </summary>
        public static string numberOfChannels {
            get {
                return ResourceManager.GetString("numberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient first name must be entered!.
        /// </summary>
        public static string patAddErrFName {
            get {
                return ResourceManager.GetString("patAddErrFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        public static string patAddErrHdr {
            get {
                return ResourceManager.GetString("patAddErrHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient surname must be entered!.
        /// </summary>
        public static string patAddErrLName {
            get {
                return ResourceManager.GetString("patAddErrLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This patient is already attached to another channel..
        /// </summary>
        public static string patDuplMsg {
            get {
                return ResourceManager.GetString("patDuplMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient already attached.
        /// </summary>
        public static string patDuplMsgH {
            get {
                return ResourceManager.GetString("patDuplMsgH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string PatEditHdr {
            get {
                return ResourceManager.GetString("PatEditHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient &quot;{0}&quot; was updated..
        /// </summary>
        public static string PatEditMsg {
            get {
                return ResourceManager.GetString("PatEditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PatHdrAddr {
            get {
                return ResourceManager.GetString("PatHdrAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        public static string PatHdrBirthDate {
            get {
                return ResourceManager.GetString("PatHdrBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PatHdrCity {
            get {
                return ResourceManager.GetString("PatHdrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string PatHdrCountry {
            get {
                return ResourceManager.GetString("PatHdrCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string PatHdrDg {
            get {
                return ResourceManager.GetString("PatHdrDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string PatHdrFName {
            get {
                return ResourceManager.GetString("PatHdrFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance Company.
        /// </summary>
        public static string PatHdrHIC {
            get {
                return ResourceManager.GetString("PatHdrHIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string PatHdrLName {
            get {
                return ResourceManager.GetString("PatHdrLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Record.
        /// </summary>
        public static string PatHdrMedRec {
            get {
                return ResourceManager.GetString("PatHdrMedRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string PatHdrMName {
            get {
                return ResourceManager.GetString("PatHdrMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string PatHdrNote {
            get {
                return ResourceManager.GetString("PatHdrNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PatHdrPhone {
            get {
                return ResourceManager.GetString("PatHdrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string PatHdrSex {
            get {
                return ResourceManager.GetString("PatHdrSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somatotype.
        /// </summary>
        public static string PatHdrSomTyp {
            get {
                return ResourceManager.GetString("PatHdrSomTyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string PatHdrZip {
            get {
                return ResourceManager.GetString("PatHdrZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string PatNewHdr {
            get {
                return ResourceManager.GetString("PatNewHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New patient &quot;{0}&quot; was created..
        /// </summary>
        public static string PatNewMsg {
            get {
                return ResourceManager.GetString("PatNewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string patSelName {
            get {
                return ResourceManager.GetString("patSelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string patSelNumber {
            get {
                return ResourceManager.GetString("patSelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year.
        /// </summary>
        public static string patSelYrOfBirth {
            get {
                return ResourceManager.GetString("patSelYrOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string PatSexFemale {
            get {
                return ResourceManager.GetString("PatSexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string PatSexMale {
            get {
                return ResourceManager.GetString("PatSexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperergic.
        /// </summary>
        public static string PatSomTypHyperergic {
            get {
                return ResourceManager.GetString("PatSomTypHyperergic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypotype.
        /// </summary>
        public static string PatSomTypHypotype {
            get {
                return ResourceManager.GetString("PatSomTypHypotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normotype.
        /// </summary>
        public static string PatSomTypNormotype {
            get {
                return ResourceManager.GetString("PatSomTypNormotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC key or button &quot;X&quot; on the end of this bar.
        /// </summary>
        public static string pressEscButton {
            get {
                return ResourceManager.GetString("pressEscButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premature procedure termination.
        /// </summary>
        public static string procAbortH {
            get {
                return ResourceManager.GetString("procAbortH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to terminate the procedure prematurely?.
        /// </summary>
        public static string procAbortQ {
            get {
                return ResourceManager.GetString("procAbortQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pswempty {
            get {
                object obj = ResourceManager.GetObject("pswempty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords match.
        /// </summary>
        public static string pswMatchMsg {
            get {
                return ResourceManager.GetString("pswMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Passwords do not match *.
        /// </summary>
        public static string pswNotMatchMsg {
            get {
                return ResourceManager.GetString("pswNotMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application and device are restarted..
        /// </summary>
        public static string restartMsg {
            get {
                return ResourceManager.GetString("restartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this point, you can not restart the device..
        /// </summary>
        public static string restartNo {
            get {
                return ResourceManager.GetString("restartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restart device?.
        /// </summary>
        public static string restartQ {
            get {
                return ResourceManager.GetString("restartQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device restart.
        /// </summary>
        public static string restartQH {
            get {
                return ResourceManager.GetString("restartQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the database was not successful..
        /// </summary>
        public static string restoreKO {
            get {
                return ResourceManager.GetString("restoreKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was restored from backup at {0}.
        /// </summary>
        public static string restoreOK {
            get {
                return ResourceManager.GetString("restoreOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restore database from previous backup?.
        /// </summary>
        public static string restoreQ {
            get {
                return ResourceManager.GetString("restoreQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the database.
        /// </summary>
        public static string restoreQH {
            get {
                return ResourceManager.GetString("restoreQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap savedatabase {
            get {
                object obj = ResourceManager.GetObject("savedatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1050000446.
        /// </summary>
        public static string serNum {
            get {
                return ResourceManager.GetString("serNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application and device are switched off..
        /// </summary>
        public static string shutdownMsg {
            get {
                return ResourceManager.GetString("shutdownMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this point, you can not switch off the device..
        /// </summary>
        public static string shutdownNo {
            get {
                return ResourceManager.GetString("shutdownNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to shutdown the device?.
        /// </summary>
        public static string shutdownQ {
            get {
                return ResourceManager.GetString("shutdownQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device shutdown.
        /// </summary>
        public static string shutdownQH {
            get {
                return ResourceManager.GetString("shutdownQH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has signed in.
        /// </summary>
        public static string signedInUser {
            get {
                return ResourceManager.GetString("signedInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string signedNotMsg {
            get {
                return ResourceManager.GetString("signedNotMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        public static string signedOutMsg {
            get {
                return ResourceManager.GetString("signedOutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has signed out.
        /// </summary>
        public static string signedOutUser {
            get {
                return ResourceManager.GetString("signedOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login {0} failed.
        /// </summary>
        public static string signedUnsuccessful {
            get {
                return ResourceManager.GetString("signedUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inicialization started..
        /// </summary>
        public static string startInitMsg {
            get {
                return ResourceManager.GetString("startInitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started....
        /// </summary>
        public static string startMsg {
            get {
                return ResourceManager.GetString("startMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running..
        /// </summary>
        public static string startMsg1 {
            get {
                return ResourceManager.GetString("startMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicialization of startup....
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap switchoff {
            get {
                object obj = ResourceManager.GetObject("switchoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-test in progress....
        /// </summary>
        public static string testChannel {
            get {
                return ResourceManager.GetString("testChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication between computer and device is interrupted, self-test has not occurred..
        /// </summary>
        public static string testChError0 {
            get {
                return ResourceManager.GetString("testChError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all channels started: {0}.
        /// </summary>
        public static string testChError11 {
            get {
                return ResourceManager.GetString("testChError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diode of channel {0} does not light red.
        /// </summary>
        public static string testChError12 {
            get {
                return ResourceManager.GetString("testChError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diode of channel {0} does not light green.
        /// </summary>
        public static string testChError13 {
            get {
                return ResourceManager.GetString("testChError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diode of channel {0} does not light blue.
        /// </summary>
        public static string testChError14 {
            get {
                return ResourceManager.GetString("testChError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient HV voltage on channel {0}.
        /// </summary>
        public static string testChError2 {
            get {
                return ResourceManager.GetString("testChError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect the headset from the channel {0}.
        /// </summary>
        public static string testChError31 {
            get {
                return ResourceManager.GetString("testChError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too high impedance on channel {0}.
        /// </summary>
        public static string testChError32 {
            get {
                return ResourceManager.GetString("testChError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stress at channel load {0} does not match the tolerance ({1}). Attenuation coefficient = {2}.
        /// </summary>
        public static string testChError4 {
            get {
                return ResourceManager.GetString("testChError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of current limitation at 10 mA on channel {0}.
        /// </summary>
        public static string testChError5 {
            get {
                return ResourceManager.GetString("testChError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HV voltage drop at maximum of load of channel {0}.
        /// </summary>
        public static string testChError6 {
            get {
                return ResourceManager.GetString("testChError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of too high current impedance at 10 mA on channel {0}.
        /// </summary>
        public static string testChError7 {
            get {
                return ResourceManager.GetString("testChError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors during self-test.
        /// </summary>
        public static string testChErrors {
            get {
                return ResourceManager.GetString("testChErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication dongle....
        /// </summary>
        public static string testDongle {
            get {
                return ResourceManager.GetString("testDongle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap undeleteuser {
            get {
                object obj = ResourceManager.GetObject("undeleteuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap useradd {
            get {
                object obj = ResourceManager.GetObject("useradd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap userdelete {
            get {
                object obj = ResourceManager.GetObject("userdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap useredit {
            get {
                object obj = ResourceManager.GetObject("useredit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string UserEditHdr {
            get {
                return ResourceManager.GetString("UserEditHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; was updated..
        /// </summary>
        public static string UserEditMsg {
            get {
                return ResourceManager.GetString("UserEditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UserHdrLang {
            get {
                return ResourceManager.GetString("UserHdrLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserHdrLogin {
            get {
                return ResourceManager.GetString("UserHdrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserHdrName {
            get {
                return ResourceManager.GetString("UserHdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserHdrRole {
            get {
                return ResourceManager.GetString("UserHdrRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap userlist {
            get {
                object obj = ResourceManager.GetObject("userlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string UserNewHdr {
            get {
                return ResourceManager.GetString("UserNewHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user &quot;{0}&quot; was created..
        /// </summary>
        public static string UserNewMsg {
            get {
                return ResourceManager.GetString("UserNewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string UserRoleAdmin {
            get {
                return ResourceManager.GetString("UserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserRoleUser {
            get {
                return ResourceManager.GetString("UserRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database compression performed..
        /// </summary>
        public static string vacuumMsg {
            get {
                return ResourceManager.GetString("vacuumMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
